//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_Club_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizer
    {
        public int OrgID { get; set; }
        public string date { get; set; }
        public string type { get; set; }
        public string duration { get; set; }
        public int trainerID { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
