//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_Club_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int age { get; set; }
        public int height { get; set; }
        public int weight { get; set; }
        public int userID { get; set; }
        public string gender { get; set; }
        public int loginID { get; set; }
        public int userContactID { get; set; }
    
        public virtual UserContact UserContact { get; set; }
        public virtual UserLog UserLog { get; set; }
    }
}
